### ISSUE TITLE
Publish a community roster featuring ambassadors and maintainers

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-organization.github.io#10]
Would our home page benefit from a prettier version of our [community roster](https://github.com/open-organization/governance/blob/master/community-roster.md) specifically highlighting [ambassadors and maintainers](https://github.com/open-organization/governance/blob/master/community-roles.md)?

**Comment by gaurav24072002** [comment]
I would like to work on this project please assign it to me and guide me as it's my first open source project..... I assure you that I will work to the best of which I can...

**Comment by semioticrobotic** [comment]
Hi @gaurav24072002! Thanks for your interest in this project.

If this is your first time participating in an open source project, this is perhaps not the best issue with which to begin. I might suggest something in another repository labeled ``Easyfix``. Issues with this label are meant to be accessible to beginners. [This is a good one](https://github.com/open-organization/open-org-distributed-work-guide/issues/43), for example.

**Comment by semioticrobotic** [comment]
We now have a basic page live at ``theopenorganization.org/roster``.
