### ISSUE TITLE
Update home page social media icons

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-organization.github.io#12]
Now that we're on LinkedIn, our home page could use an icon that directs visitors to our community there. It can simply sit alongside links to GitHub and Twitter.

As part of this work, we should refresh all social media icons, make them more stylistically consistent, and adjust their respective spacing so they have a bit less padding.

- [x] Create new social media icon set (including new icon for LinkedIn)
- [x] Update project home page with new social media icon set

**Comment by gaurav24072002** [comment]
Hey! I am interested in solving this issue... Please assign it to me...

**Comment by gaurav24072002** [comment]
I have send a pull request (i.e. #14 ) of adding the LinkedIn icon to site  . now you can merge it

**Comment by semioticrobotic** [comment]
Thank for this. As per my note in the pull request, I've closed the thread because your solution doesn't reflect our preferred implementation for icons on the home page.

Additionally, however, we'll likely need to update **all** social media icons, not just LinkedIn, in the near future, so we'll coordinate all that work at once. I will update the title of this issue to reflect the expanded scope. Apologies for the confusion.

**Comment by semioticrobotic** [comment]
Homepage icon for LinkedIn [is now live](https://github.com/open-organization/open-organization.github.io/commit/cdf49720f98dbd48f15335a253820c0bbb21ac10) and I've [edited all social media icons](https://github.com/open-organization/open-organization.github.io/commit/6b0be64a8f4909d7c66cdab7fb88aafff8bc077c) to remove some of the padding around the buttons.
