### ISSUE TITLE
About page roles link goes to the wrong place

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-organization.github.io#17]
On this page > https://theopenorganization.org/about/
"play different roles" goes to https://github.com/open-organization/governance/wiki/Community-Roles
should go to https://github.com/open-organization/governance/wiki/Roles

**Comment by semioticrobotic** [comment]
Thank you for finding and reporting this! I will prioritize as part of the upcoming Website Update Extravaganza.

**Comment by semioticrobotic** [comment]
Fixed this! Thanks again for reporting, @LauraHilliger.
