### ISSUE TITLE
Create a toggle menu for mobile

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-organization.github.io#19]
As discussed off the back of [this PR](https://github.com/open-organization/open-organization.github.io/pull/18), we need to mess with the menu becuase it's janky on mobile. Hamburgers to the rescue.

**Comment by semioticrobotic** [comment]
Thanks, @LauraHilliger. I think the best place to begin is by investigating [that Jekyll documentation you found](https://jekyllcodex.org/without-plugin/toggle-menu/). I will give it a read.

**Comment by LauraHilliger** [comment]
PR sent https://github.com/open-organization/open-organization.github.io/pull/24
