### ISSUE TITLE
Page header might become more accessible

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-organization.github.io#2]
In a [separate thread](https://www.theopenorganization.community/t/building-our-new-showcase-on-the-web/123/16), @HeidiHVL writes:

> I feel like the “buttons” are hard to see. White on aqua can be tough ...

In response to this, we might consider refreshing the site's primary navigation links. We might also adjust overall implementation of the site's header.

**Comment by LauraHilliger** [comment]
Howdy! Guess who's backkkkk!! We should definitely work on the contrast for accessibility purposes as the color scheme currently [fails all the things](https://webaim.org/resources/contrastchecker/). Unfortunately, none of the Turquoise colors in our palette are appropriate for the screen

![image](https://user-images.githubusercontent.com/539017/92454321-ad326f80-f1c0-11ea-9c8c-84464a8528dc.png)

Shall we just switch to the Navy? It passes both navy on white and white on navy. There are other colors that pass the test too.

**Comment by semioticrobotic** [comment]
Oh wow. Yikes. Thanks so much for raising this, @LauraHilliger. Yes, let's for sure experiment with something else. Navy is my favorite color, so of course I don't mind starting there. :smile: 

I can add to my worklist for this week. Alternatively, if you want to fiddle with the stylesheet, you should now have proper access as a duly designated member of the web team (sorry about before).

And, WELCOME BACK!!

**Comment by semioticrobotic** [comment]
Header and headings are now set in our primary shade of navy. See what you think, @LauraHilliger and @HeidiHVL!

**Comment by semioticrobotic** [comment]
Ultimately, if inversion proves to be the heart of the issue, we could consider keeping the backgrounds of both the header and the body sections white, using the full-color version of the logo, and re-inverting navigation, etc.

**Comment by jimmysjolund** [comment]
While the contrast between the white text and the blueish button is now better, the button itself doesn't stand out much from the blue background. The blue/navy background also make us use the all white logo. This is where it is mostly visible and I think it's nice if the three colour logo would be showing at the front page.

**Comment by semioticrobotic** [comment]
I see. Thanks, @jimmysjolund. It seems to me, then, that the next strategy to try will be to un-invert the header, turn all buttons black (or another color from our palette) and use the full-color version of the logo. That's fine with me, though it will take a little work (I'll need to do image editing in addition to coding restructuring), but I think I can get us there soon.

**Comment by semioticrobotic** [comment]
Okay, well, [that didn't actually take as long](https://github.com/open-organization/open-organization.github.io/commit/b3b3459bf9384ddbee135c14d84d8a3a82997a35) as I suspected it might.

@jimmysjolund, @LauraHilliger, @HeidiHVL: Please take a look and see if the re-imagined page header seems better to you in all regards. I'm guessing we'll need to play with colors, etc., but we can certainly do that!

**Comment by HeidiHVL** [comment]
It looks better! 
I noticed that the button text is dark hot pink. My artisty painterly perpective is to use colors that all go together, ie those that are adjacent to each other and in this case that means those that are found on the end of the spectrum with teal and blue - so purple rather than pink. (If that makes sense. ) 
Thanks for your work on this. It's MUCH easier to read.

**Comment by semioticrobotic** [comment]
Our new branded color palette does include a purple! I can switch to that as the accent color and we can see how it looks. Thanks for the feedback.

**Update:** [Done.](https://github.com/open-organization/open-organization.github.io/commit/f4b1dbf610d2380f0a752a1fb726fd1edd2af13d) See what you think, @HeidiHVL.

**Comment by HeidiHVL** [comment]
thanks @semioticrobotic it flows better to my eyes... but I will say that the medium tone purple is still harder to "see" and focus on than a darker one. It's just my old eyes!  :)

**Comment by semioticrobotic** [comment]
I do think you're right though, @HeidiHVL. I can experiment with using the "dark" variant of our brand's pallet to see if that makes a difference.

**Update:** [Done again.](https://github.com/open-organization/open-organization.github.io/commit/9d40e3b9b8be3d30bce52e51d7c0b8cc424ab3b1) Thanks, @HeidiHVL!

**Comment by semioticrobotic** [comment]
I think we resolved this, so I am going to close for now. Always happy to keep iterating for the sake of accessibility, of course.
