### ISSUE TITLE
Find a new jekyll theme

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-organization.github.io#25]
Our original template was selected for ease of use, but it would appear that it is no longer fit for purpose. We need to find a new one. The community has asked for a theme that has:

- more focus on images
- something that can showcase inspirational quotes/videos/case studies
- a greater variety of page styles (e.g., individual pages for books that look and feel different from homepage)
- good code so that it continues to load quickly and work well on multiple screen sizes
- findability features (e.g. analytics, SEO)

In addition, maintainers want something that is easy to maintain and update ;) We can use this ticket to try and find something to start from.

[Here are all the themes.](https://jekyllthemes.io/)

**Comment by semioticrobotic** [comment]
I would also add:

- open source

... just in case there happen to be templates that *aren't* open source for some reason. :shrug:

**Comment by semioticrobotic** [comment]
So far, I am liking [Minimal Mistakes](https://jekyllthemes.io/theme/minimal-mistakes). A few reasons why, in no particular order of importance.

- **It's open source.** Available [under the MIT License](https://mmistakes.github.io/minimal-mistakes/docs/license/).
- **It's expressly compatible with GitHub Pages.** Most themes are, but I like knowing that something we choose is explicitly documented to work with the hosting platform we're using.
- **It's not "blog-first," as so many themes seem to be.** We're not looking at a website that features blog-style content (at least not right now, and at least not primarily)
- **It's popular and well-documented.** I've seen it in use (under various guises) before and understand it's got [a strong contributor base](https://github.com/mmistakes/minimal-mistakes). I can understand the documentation. I know where to go for help if we need it.
- **It's flexible.** We should be able to theme this according to our brand guidelines and make it our own rather quickly and easily.
- **It features multiple page styles.** This is something we've wanted for quite a while and this theme just does it straight away.
- **It features space for bold images.** The community has been asking for a site with more images and this template lays groundwork for that look.

**Comment by LauraHilliger** [comment]
Looks like a big improvement! I love it, shall we create a branch so we can work in peace and then when we have somehting to show, we...show it? Or how should we get started?

**Comment by semioticrobotic** [comment]
Okay! Here's what I did.

1. Created a new project repository, `new-website`, to house the work. I agree that the best approach would be to work in a branch but I wanted us to be able to have a live, shared test environment so we're working with the same point of reference. Having a new repo means we can have a new GitHub Pages instance. I populated the repo with a `.gitignore` specifically for Jekyll work.
2. I cloned the new repo, downloaded the theme, extracted it, and configured it according to the documentation. I used the "Remote theme method" [outlined there](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method). So our configuration files reflect that setup. Feel free to check my work!
3. I fired up GitHub Pages and let it do its thing. Now if you go to `http://theopenorganization.org/new-website/` you should see a blank canvas.

And that's all I was able to do for now (sorry), but I can help more later if you'd like. In the meantime, if you clone the `new-website` repo you should have a working copy of everything I've been able to accomplish so far. Obviously, feel free to begin working and pushing your changes straight to the repository to update the working site. I think that's the best way to stay synced up. But if you have other preference or ideas, please do share.

**Comment by LauraHilliger** [comment]
HIIII I was figuring loads of stuff out, and I'm committed to this template now! Nowhere close to DONE, loads of design to do, but I started to figure out the techie bits and loooookkkkk:

- http://theopenorganization.org/new-website/books/
- http://theopenorganization.org/new-website/about/
- http://theopenorganization.org/new-website/definitions/

I was just playing around with the little headers, wanted to see what the splash images did. They hero-stretch, fyi, and I didn't want to change that, but I'm not at all married to these little headers. I still have loads to figure out on the collections and galleries feature, and I want to mess with layouts and stuff.

@semioticrobotic if you have time and are looking around and thinking "we should do X and we should do Y" maybe file tickets if you don't have tinker time? I'm excited! We're making progress!

**Comment by semioticrobotic** [comment]
Wow! Nice work, @LauraHilliger! Great strides.

In the days ahead I will poke around and tinker, even file some tickets!

Thank you!
