### ISSUE TITLE
Add @media css for floating images

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-organization.github.io#6]
Our books page uses floating images, but our css doesn't adjust for mobile. Just need to add the media css to fix er up:

https://theopenorganization.org/books/

**Comment by semioticrobotic** [comment]
The solution is to implement a series of ``@include`` modifiers that adjust the screen for large, medium, and small viewports. You can see an example in [the way we've styled the site header image](https://github.com/open-organization/open-organization.github.io/blob/master/assets/css/style.scss). Should be a quick fix and I can get on it soon if no one else wants to take it.

**Comment by LauraHilliger** [comment]
oh. hahahh WE SHOULD BE COWORKING. Just did this: https://github.com/open-organization/open-organization.github.io/pull/7

will leave the issue open though so we can discuss which is the better way? I dunno!

**Comment by LauraHilliger** [comment]
Changed based on our conversation. I left Large and Medium at a default size of 35% (we can change this if you think it should be slightly bigger or smaller: https://github.com/open-organization/open-organization.github.io/pull/7

**Comment by semioticrobotic** [comment]
It's beautiful. Thank you so much. This is now merged and live!
