### ISSUE TITLE
look into subnavigation options in cayman

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-organization.github.io#8]
We're using the Cayman template in Jekyll, and thinking about how to use sub-navigation either in the pages or in the main navigation. Will research options here and make a proposal.

**Comment by vennelakoilada362** [comment]
i want to work on this issue, please assign it to me and please guide me

**Comment by semioticrobotic** [comment]
Thanks for pitching in, @vennelakoilada362! We're happy for your help.

@LauraHilliger opened this issue, so I believe she'll be able to offer the best guidance here. But I will start by saying I *think* that what we're trying to do here is investigate the possibility of updating our website (which uses the Cayman theme, heavily tweaked) to support more complex menus.

At the moment, our navigation menu only allows one link per item. We were wondering if there was any way we could augment the theme or the template to allow more options (say, if one hovered over the "Books" item with a mouse, a dropdown would appear with links to the entire book series).

We are very much in the exploratory phase here, and would welcome your feedback and insights.
